AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'config/**/*'
    - 'script/**/*'
    - '**/Gemfile'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"